using System;
using UnityEngine;

// Written by Seth Riddensdale
namespace pricenerds3D
{
    /// <summary>
    /// This is a scriptable object that is automatically generated by the importer
    /// It contains all animation data to be interpreted by a clip controller
    /// </summary>
    [Serializable]
    public class P3D_ClipData : ScriptableObject
    {
        public string clipName;
    }
}
