using System;
using UnityEngine;

// Written by Seth Riddensdale
namespace pricenerds3D
{
    /// <summary>
    ///     This is a scriptable object that is automatically generated by the importer
    ///     It contains all animation data to be interpreted by a clip controller
    /// </summary>
    [Serializable]
    public class P3D_ClipData : ScriptableObject
    {
        public string clipName;
        public P3D_Clip clip;
    }

    [Serializable]
    public class P3D_Clip
    {
        [SerializeField] private P3D_Keyframe[] _keyframes;
        [SerializeField] private P3D_Sample[] _samples;
        [SerializeField] private float _durationSeconds;
        [SerializeField] private float _durationInverse;


        public P3D_Clip(uint sampleCount)
        {
            var keyframeCount = sampleCount - 1;
            _samples = new P3D_Sample[sampleCount];
            _keyframes = new P3D_Keyframe[keyframeCount];

            for (var i = 0; i < keyframeCount; i++)
                _keyframes[i] = new P3D_Keyframe
                {
                    index = (uint)i,
                    sampleIndex0 = (uint)i,
                    sampleIndex1 = (uint)(i + 1),
                    duration = 0f
                };

            for (var i = 0; i < sampleCount; i++) _samples[i] = new P3D_Sample((uint)i);
        }

        public P3D_Keyframe[] keyframes => _keyframes;
        public P3D_Sample[] samples => _samples;
        public float durationSeconds => _durationSeconds;
        public float durationInverse => _durationInverse;

        // TODO: importer should use this
        public void SetDuration(float duration)
        {
            _durationSeconds = duration;
            _durationInverse = duration > 0f ? 1f / duration : 0f;
        }

        public void SetKeyframeDuration(int index, float duration)
        {
            _keyframes[index].duration = duration;
            _keyframes[index].durationInverse = duration > 0f ? 1f / duration : 0f;
        }
    }


    [Serializable]
    public struct P3D_Keyframe
    {
        public uint index;
        public uint sampleIndex0;
        public uint sampleIndex1;
        public float duration;
        public float durationInverse;

        public P3D_Sample GetSample0(P3D_Clip clip)
        {
            return clip.samples[sampleIndex0];
        }

        public P3D_Sample GetSample1(P3D_Clip clip)
        {
            return clip.samples[sampleIndex1];
        }
    }

    [Serializable]
    public class P3D_Sample
    {
        [SerializeField] private uint _index;

        public Vector3 localTranslation;
        public Quaternion localRotation;
        public Vector3 localScale;


        public P3D_Sample(uint index)
        {
            _index = index;
            localTranslation = Vector3.zero;
            localRotation = Quaternion.identity;
            localScale = Vector3.one;
        }

        public uint index => _index;

        public void SetPose(Vector3 translation, Quaternion rotation, Vector3 scale)
        {
            localTranslation = translation;
            localRotation = rotation;
            localScale = scale;
        }
    }
}